apiVersion: v1
kind: ServiceAccount
metadata:
  name: ottawa-fleet-app
  labels:
    {{- include "ottawa-fleet.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
automountServiceAccountToken: false
