apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "ottawa-fleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "ottawa-fleet.selectorLabels" (dict "root" . "component" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ottawa-fleet.selectorLabels" (dict "root" . "component" "web") | nindent 8 }}
      annotations:
        {{- include "ottawa-fleet.podAnnotations" (dict "root" . "image" .Values.images.web) | nindent 8 }}
    spec:
      serviceAccountName: ottawa-fleet-app
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 5
      {{- include "ottawa-fleet.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      containers:
        - name: web
          image: {{ include "ottawa-fleet.image" .Values.images.web | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_BACKGROUND_COLOR
              value: {{ .Values.web.backgroundColor | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.ports.web }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          readinessProbe:
            httpGet: {path: /, port: http}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet: {path: /, port: http}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "ottawa-fleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "ottawa-fleet.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ports.web }}
      targetPort: http
      protocol: TCP
